name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"  # setiap 12 jam
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write  # dibutuhkan untuk push ke branch output

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
        env:
          # Gunakan token pribadi agar bisa akses kontribusi privat
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
